/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Währungsrechner;

/**
 *
 * @author joel_
 */
public class Währungsrechner extends javax.swing.JFrame {
    
    String[] währungsUnits = {
    "Units",
    "US-Dollar",
    "Euro",
    "Japanischer Yen",
    "Pfund Sterling",
    "Australischer Dollar",
    "Kanadischer Dollar",
    "Schweizer Franken" ,
    "Chinesischer Yuan",
    "Hongkong-Dollar",
    "Neuseeländischer Dollar"
    };
    
    double US_Dollar = 1.08;
    double Euro = 0.97;
    double Japanischer_Yen = 122.76;
    double Pfund_Sterling = 0.82;
    double Australischer_Dollar = 1.53;
    double Kanadischer_Dollar = 1.40;
    double Schweizer_Franken = 1.04;
    double Chinesischer_Yuan = 6.90;
    double Neuseeländischer_Dollar = 1.61;

    /**
     * Creates new form Währungsrechner
     */
    public Währungsrechner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        zweitesLand = new javax.swing.JComboBox<>();
        erstesLand = new javax.swing.JComboBox<>();
        txt2 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        zweiteUnit = new javax.swing.JLabel();
        ersteUnit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        zweitesLand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wähle ein Land", "USA", "EU-Länder", "Japan", "Großbritannien", "Australien", "Kanada", "Schweiz", "China", "Neuseeland" }));
        zweitesLand.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                zweitesLandItemStateChanged(evt);
            }
        });

        erstesLand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wähle ein Land", "USA", "EU-Länder", "Japan", "Großbritannien", "Australien", "Kanada", "Schweiz", "China", "Neuseeland", "" }));
        erstesLand.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                erstesLandItemStateChanged(evt);
            }
        });
        erstesLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erstesLandActionPerformed(evt);
            }
        });

        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });

        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt1KeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Währungsumrechner");

        jLabel2.setText("Währung von");

        jLabel3.setText("Währung zu");

        jButton1.setText("Umrechnen");
        jButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jButton1ItemStateChanged(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        zweiteUnit.setText("Währung");

        ersteUnit.setText("Währung");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(zweitesLand, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zweiteUnit)
                            .addComponent(ersteUnit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(erstesLand, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(241, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(45, 45, 45)
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ersteUnit)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zweitesLand, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zweiteUnit)
                .addGap(58, 58, 58)
                .addComponent(jButton3)
                .addGap(83, 83, 83))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(149, 149, 149)
                    .addComponent(erstesLand, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(330, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void erstesLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erstesLandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_erstesLandActionPerformed

    private void erstesLandItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_erstesLandItemStateChanged
       
        int position = erstesLand.getSelectedIndex();
        
        ersteUnit.setText(währungsUnits[position]);
        
    }//GEN-LAST:event_erstesLandItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void zweitesLandItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_zweitesLandItemStateChanged
        
        int position = zweitesLand.getSelectedIndex();
        
        zweiteUnit.setText(währungsUnits[position]);
        
    }//GEN-LAST:event_zweitesLandItemStateChanged

    private void jButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jButton1ItemStateChanged
       
       
    }//GEN-LAST:event_jButton1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double wechselBetrag = Double.parseDouble(txt1.getText());
        double BetragInFranken =  0.0;  
        
        
        switch(erstesLand.getSelectedItem().toString())
        {
            case "USA" : BetragInFranken = wechselBetrag / US_Dollar; break;
            case "EU-Länder" : BetragInFranken = wechselBetrag / Euro; break;
            case "Japan" : BetragInFranken = wechselBetrag / Japanischer_Yen; break;
            case "Grossbritannien" : BetragInFranken = wechselBetrag / Pfund_Sterling; break;
            case "Australien" : BetragInFranken = wechselBetrag / Australischer_Dollar; break;
            case "Kanada" : BetragInFranken = wechselBetrag / Kanadischer_Dollar; break;
            case "Schweiz" : BetragInFranken = wechselBetrag / Schweizer_Franken; break;
            case "China" : BetragInFranken = wechselBetrag / Chinesischer_Yuan; break;
            case "Neuseeland" : BetragInFranken = wechselBetrag / Neuseeländischer_Dollar; break;
            default:BetragInFranken = 0.0;
        }
        
        double BetragUmgerechnet = 0.0;
        switch(zweitesLand.getSelectedItem().toString())
        {
            case "USA" : BetragUmgerechnet = BetragInFranken * US_Dollar; break;
            case "EU-Länder" : BetragUmgerechnet = BetragInFranken * Euro; break;
            case "Japan" : BetragUmgerechnet = BetragInFranken * Japanischer_Yen; break;
            case "Grossbritannien" : BetragUmgerechnet = BetragInFranken * Pfund_Sterling; break;
            case "Australien" : BetragUmgerechnet = BetragInFranken * Australischer_Dollar; break;
            case "Kanada" : BetragUmgerechnet = BetragInFranken * Kanadischer_Dollar; break;
            case "Schweiz" : BetragUmgerechnet = BetragInFranken * Schweizer_Franken; break;
            case "China" : BetragUmgerechnet = BetragInFranken * Chinesischer_Yuan; break;
            case "Neuseeland" : BetragUmgerechnet = BetragInFranken * Neuseeländischer_Dollar; break;
            default:BetragUmgerechnet = BetragInFranken * 0.0;
        }
        
        String value = String.format("%.2f",BetragUmgerechnet);
        txt2.setText(value); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    private void txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Währungsrechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Währungsrechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Währungsrechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Währungsrechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Währungsrechner().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ersteUnit;
    private javax.swing.JComboBox<String> erstesLand;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JLabel zweiteUnit;
    private javax.swing.JComboBox<String> zweitesLand;
    // End of variables declaration//GEN-END:variables
}
